name: firebase_firestore_vm
description: A starting point for Dart libraries or applications.
version: 0.0.1
author: long1eu <home@long.1eu>

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  firebase_core_vm:
    git:
      url: https://github.com/fluttercommunity/firebase_dart_sdk
      path: firebase_core_vm
  firebase_database_collection_vm:
    git:
      url: https://github.com/fluttercommunity/firebase_dart_sdk
      path: firebase_database_collection_vm
  _firebase_internal_vm:
    git:
      url: https://github.com/fluttercommunity/firebase_dart_sdk
      path: _firebase_internal_vm

  protobuf: ^1.0.1
  grpc: ^2.1.3
  rxdart: ^0.23.1


dev_dependencies:
  test: ^1.13.0
  mockito: ^4.1.1
  moor_ffi: ^0.4.0
  uuid: ^2.0.4

latest_commit: 557749eeddbecdc274498760bddbae7c230e6765