name: example
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: long1eu <lung.razvan@gmail.com>

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  email_validator: ^1.0.4
  intl: ^0.16.1
  uuid: ^2.0.4
  crypto: ^2.1.4
  firebase_auth:
    path: ../../

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.12.0
