name: firebase_flutter
description: A Flutter wrapper over the Firebase Dart SDK.
version: 0.0.1
author: long1eu
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^1.4.5
  firebase_auth: ^0.15.0+1
  sqflite: ^1.1.7+3
  connectivity: ^0.4.5+7

  firebase_common_dart:
    git:
      url: https://github.com/fluttercommunity/firebase_dart_sdk
      path: firebase_common_dart
  firebase_firestore_dart:
    git:
      url: https://github.com/fluttercommunity/firebase_dart_sdk
      path: firebase_firestore_dart

flutter:
  plugin:
    androidPackage: com.google.firebase.firebaseflutter
    pluginClass: FirebaseFlutterPlugin
