name: firebase_core_vm_example
description: A new Flutter project.

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  shared_preferences: ^0.5.6+2
  connectivity: ^0.4.8+1
  firebase_core_vm:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true