name: firebase_core_vm_example
description: Example app for firebase_core_vm

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3

  hive: ^1.4.4
  path_provider: '>=1.6.14 <2.0.0'
  connectivity: '>=0.4.9 <2.0.0'
  connectivity_linux: ^0.0.0-dev.1

  firebase_core_vm:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true