name: firebase_auth
description: A starting point for Dart libraries or applications.
version: 0.0.1
homepage: https://github.com/fluttercommunity/firebase_flutter_sdk
author: long1eu <home@long1.eu>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  firebase_common:
    path: ../firebase_common
  firebase_internal:
    path: ../firebase_internal
  built_value: 6.8.2
  built_collection: 4.2.2
  hive: ^1.1.1
  rxdart: ^0.22.6

dev_dependencies:
  test: ^1.6.8
  build_runner: 1.7.1
  built_value_generator: 6.8.2
