name: firebase_auth
description: A starting point for Dart libraries or applications.
version: 0.0.1
homepage: https://github.com/fluttercommunity/firebase_flutter_sdk
author: long1eu <home@long1.eu>

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  firebase_common:
    git:
      url: https://github.com/fluttercommunity/firebase_dart_sdk
      path: firebase_common
  firebase_internal:
    git:
      url: https://github.com/fluttercommunity/firebase_dart_sdk
      path: firebase_internal

  built_value: ^7.0.9
  built_collection: ^4.3.2
  hive: ^1.4.1+1
  rxdart: ^0.23.1
  googleapis: ^0.54.0
  googleapis_auth: ^0.2.11+1

dev_dependencies:
  test: ^1.12.0
  build_runner: ^1.7.4
  built_value_generator: ^7.0.9
