name: connectivity_linux
description: Linux implementation for `connectivity` plugin
version: 0.0.0-dev.1
homepage: https://github.com/fluttercommunity/firebase_dart_sdk/tree/develop/connectivity_linux

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  connectivity_platform_interface: ^1.0.6
  dbus: ^0.0.0-dev.16

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      linux:
        dartPluginClass: ConnectivityLinuxPlugin
        pluginClass: none