name: firebase_auth_example
description: Demonstrates how to use the firebase_auth plugin.
author: Flutter Team <flutter-dev@googlegroups.com>

dependencies:
  flutter:
    sdk: flutter

  firebase_auth:
    git:
      url: https://github.com/fluttercommunity/firebase_dart_sdk
      ref: develop
      path: firebase_auth
  google_sign_in: ^4.1.4
  uuid: ^2.0.4
  path_provider: ^1.6.1
  path_provider_macos: ^0.0.4

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: any

flutter:
  uses-material-design: true
