name: firebase_firestore
description: A starting point for Dart libraries or applications.
version: 0.0.1+1
author: long1eu <home@long.1eu>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  firebase_common:
    git:
      url: https://github.com/fluttercommunity/firebase_dart_sdk
      path: firebase_common

  firebase_database_collection:
    git:
      url: https://github.com/fluttercommunity/firebase_dart_sdk
      path: firebase_database_collection

  protobuf: ^0.13.15
  grpc: ^2.1.1
  rxdart: ^0.22.2

dev_dependencies:
  test: ^1.6.8
  mockito: ^4.1.0
  dart_sqlite:
    git:
      url: https://github.com/long1eu/dart_sqlite
      path: dart

latest_commit: 0b672e8460bc8bcc0389e982819c12633847af56