name: firebase_firestore
description: A starting point for Dart libraries or applications.
version: 0.0.1
author: long1eu <home@long.1eu>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  firebase_common:
    path: ../firebase_common
  firebase_auth:
    path: ../firebase_auth
  firebase_database_collection:
    path: ../firebase_database_collection

  protobuf: ^0.10.2
  grpc: ^0.6.4

dev_dependencies:
  test: ^1.0.0
  mockito: ^3.0.0
  sqlite:
    git: https://github.com/long1eu/dart-sqlite
    #path: ../../../IdeaProjects/dart-sqlite