name: firebase_firestore
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: long1eu <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  firebase_common:
    path: ../firebase_common
  firebase_auth:
    path: ../firebase_auth
  quiver: '>=2.0.0 <3.0.0'
  protobuf: ^0.10.2
  grpc: ^0.6.4

dev_dependencies:
  test: ^1.0.0
