name: firebase_auth_dart_example
description: Exacmple app for firebase_auth_dart

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  firebase_dynamic_links: ^0.5.0+11

  google_sign_in: ^4.1.4
  google_sign_in_dartio: ^0.0.6
  firebase_core: ^0.4.4+2
  firebase_core_dart: ^0.0.1
  firebase_auth_dart:
    path: ../

dependency_overrides:
  firebase_auth: 0.15.3
  firebase_core: 0.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true