name: firebase_auth_dart_example
description: Example app for firebase_auth_dart

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  firebase_dynamic_links: ^0.6.0

  google_sign_in: ^4.5.3
  google_sign_in_dartio: ^0.0.8
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  firebase_core_dart: ^0.0.4
  firebase_auth_dart:
    path: ../

dependency_overrides:
  rxdart: ^0.24.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true