name: firebase_core_vm
description: Dart implementation of Firebase Core SDK that provides FirebaseApps used by all Firebase services
version: 0.0.9
homepage: https://github.com/fluttercommunity/firebase_flutter_sdk

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  _firebase_internal_vm: ^0.0.2+1
  rxdart: ^0.24.1
  meta: '>=1.0.0 <2.0.0'
  hive: ^1.4.4
  intl: ^0.16.1

dev_dependencies:
  test: '>=1.0.0 <2.0.0'

latest_commit: 76597dbf96cdb3550564b93e46dc34e434c95a08
