name: firebase_common_dart
description: A starting point for Dart libraries or applications.
version: 0.0.1
homepage: https://github.com/fluttercommunity/firebase_flutter_sdk
author: long1eu <home@long1.eu>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  rxdart: ^0.23.1
  firebase_internal_dart:
    # path: ../firebase_internal_dart
    git:
      url: https://github.com/fluttercommunity/firebase_dart_sdk
      ref: develop
      path: firebase_internal_dart

dev_dependencies:
  test: ^1.12.0
 