name: cloud_firestore_vm_example
description: Example app for cloud_firestore_vm

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  shared_preferences: ^0.5.6+3
  connectivity: ^0.4.8+2
  moor_ffi: ^0.4.0
  sqflite: ^1.3.0
  cloud_firestore_vm:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true