name: tools
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  googleapis: ^0.54.0
  googleapis_beta: ^0.49.0
  googleapis_auth: ^0.2.11+1
  path: ^1.6.4
  strings: ^0.1.2
dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
