name: firebase_sdk_tools
description: Tools used by the firebase_dart_sdk to automate tasks
version: 0.0.1
repository: https://github.com/fluttercommunity/firebase_dart_sdk/tree/develop/dev/tools

environment:
  sdk: '>=2.8.0 <3.0.0'

dependencies:
  googleapis: ^0.55.0
  googleapis_beta: ^0.50.0
  googleapis_auth: ^0.2.12
  path: ^1.7.0
  strings: ^0.1.2
  xml: ^4.4.1
  args: ^1.6.0
  yaml: ^2.2.1
  meta: ^1.0.0
  crypto: ^2.0.0
  pedantic: ^1.9.0

dev_dependencies:
  test: ^1.15.3
