name: connectivity_linux_example
description: Demonstrates how to use the connectivity_linux plugin.
publish_to: 'none'

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3

  connectivity: ^0.4.9+2
  connectivity_linux:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true